package co.kuznetsov.medialib.index;

import software.amazon.awssdk.enhanced.dynamodb.TableSchema;
import software.amazon.awssdk.enhanced.dynamodb.mapper.StaticTableSchema;
import static software.amazon.awssdk.enhanced.dynamodb.mapper.StaticAttributeTags.primaryPartitionKey;
import static software.amazon.awssdk.enhanced.dynamodb.mapper.StaticAttributeTags.primarySortKey;
import static software.amazon.awssdk.enhanced.dynamodb.mapper.StaticAttributeTags.secondaryPartitionKey;
import static software.amazon.awssdk.enhanced.dynamodb.mapper.StaticAttributeTags.secondarySortKey;

/**
 * Package-private DynamoDB StaticTableSchema constants for MediaIndex.
 * Kept in a separate file to stay under the Checkstyle 500-line limit.
 */
final class MediaIndexSchemas {

    static final TableSchema<ChannelItem> CHANNEL_SCHEMA =
        StaticTableSchema.builder(ChannelItem.class)
            .newItemSupplier(ChannelItem::new)
            .addAttribute(String.class, a -> a.name("channelId")
                .getter(ChannelItem::getChannelId)
                .setter(ChannelItem::setChannelId)
                .tags(primaryPartitionKey()))
            .addAttribute(String.class, a -> a.name("channelName")
                .getter(ChannelItem::getChannelName)
                .setter(ChannelItem::setChannelName))
            .addAttribute(String.class, a -> a.name("lastVideoId")
                .getter(ChannelItem::getLastVideoId)
                .setter(ChannelItem::setLastVideoId))
            .addAttribute(String.class, a -> a.name("processingStatus")
                .getter(ChannelItem::getProcessingStatus)
                .setter(ChannelItem::setProcessingStatus))
            .addAttribute(String.class, a -> a.name("lastError")
                .getter(ChannelItem::getLastError)
                .setter(ChannelItem::setLastError))
            .addAttribute(String.class, a -> a.name("skipReason")
                .getter(ChannelItem::getSkipReason)
                .setter(ChannelItem::setSkipReason))
            .addAttribute(String.class, a -> a.name("lastVideoPublishedAt")
                .getter(ChannelItem::getLastVideoPublishedAt)
                .setter(ChannelItem::setLastVideoPublishedAt))
            .addAttribute(String.class, a -> a.name("lastVideoPublishedAtFormatted")
                .getter(ChannelItem::getLastVideoPublishedAtFormatted)
                .setter(ChannelItem::setLastVideoPublishedAtFormatted))
            .build();

    static final TableSchema<MediaItem> MEDIA_SCHEMA =
        StaticTableSchema.builder(MediaItem.class)
            .newItemSupplier(MediaItem::new)
            .addAttribute(String.class, a -> a.name("channelId")
                .getter(MediaItem::getChannelId)
                .setter(MediaItem::setChannelId)
                .tags(primaryPartitionKey()))
            .addAttribute(String.class, a -> a.name("channelName")
                .getter(MediaItem::getChannelName)
                .setter(MediaItem::setChannelName))
            .addAttribute(String.class, a -> a.name("videoId")
                .getter(MediaItem::getVideoId)
                .setter(MediaItem::setVideoId)
                .tags(primarySortKey()))
            .addAttribute(Long.class, a -> a.name("publishedAt")
                .getter(MediaItem::getPublishedAt)
                .setter(MediaItem::setPublishedAt))
            .addAttribute(String.class, a -> a.name("publishedAtFormatted")
                .getter(MediaItem::getPublishedAtFormatted)
                .setter(MediaItem::setPublishedAtFormatted))
            .addAttribute(String.class, a -> a.name("processingStatus")
                .getter(MediaItem::getProcessingStatus)
                .setter(MediaItem::setProcessingStatus))
            .addAttribute(String.class, a -> a.name("sourceType")
                .getter(MediaItem::getSourceType)
                .setter(MediaItem::setSourceType))
            .addAttribute(String.class, a -> a.name("contentType")
                .getter(MediaItem::getContentType)
                .setter(MediaItem::setContentType))
            .addAttribute(String.class, a -> a.name("inputTitle")
                .getter(MediaItem::getInputTitle)
                .setter(MediaItem::setInputTitle))
            .addAttribute(String.class, a -> a.name("outputTitle")
                .getter(MediaItem::getOutputTitle)
                .setter(MediaItem::setOutputTitle))
            .addAttribute(Long.class, a -> a.name("inputTimeSeconds")
                .getter(MediaItem::getInputTimeSeconds)
                .setter(MediaItem::setInputTimeSeconds))
            .addAttribute(String.class, a -> a.name("outputTime")
                .getter(MediaItem::getOutputTime)
                .setter(MediaItem::setOutputTime))
            .addAttribute(String.class, a -> a.name("transcriptText")
                .getter(MediaItem::getTranscriptText)
                .setter(MediaItem::setTranscriptText))
            .addAttribute(String.class, a -> a.name("summaryText")
                .getter(MediaItem::getSummaryText)
                .setter(MediaItem::setSummaryText))
            .addAttribute(String.class, a -> a.name("inputFilePath")
                .getter(MediaItem::getInputFilePath)
                .setter(MediaItem::setInputFilePath))
            .addAttribute(String.class, a -> a.name("outputAudioUrl")
                .getter(MediaItem::getOutputAudioUrl)
                .setter(MediaItem::setOutputAudioUrl))
            .addAttribute(String.class, a -> a.name("downloadTime")
                .getter(MediaItem::getDownloadTime)
                .setter(MediaItem::setDownloadTime))
            .addAttribute(String.class, a -> a.name("uploadTime")
                .getter(MediaItem::getUploadTime)
                .setter(MediaItem::setUploadTime))
            .addAttribute(String.class, a -> a.name("processingTime")
                .getter(MediaItem::getProcessingTime)
                .setter(MediaItem::setProcessingTime))
            .addAttribute(Long.class, a -> a.name("createdAt")
                .getter(MediaItem::getCreatedAt)
                .setter(MediaItem::setCreatedAt)
                .tags(secondarySortKey("feedPartition-createdAt-index")))
            .addAttribute(String.class, a -> a.name("createdAtFormatted")
                .getter(MediaItem::getCreatedAtFormatted)
                .setter(MediaItem::setCreatedAtFormatted))
            .addAttribute(Boolean.class, a -> a.name("isPlayed")
                .getter(MediaItem::getIsPlayed)
                .setter(MediaItem::setIsPlayed))
            .addAttribute(Long.class, a -> a.name("ttl")
                .getter(MediaItem::getTtl)
                .setter(MediaItem::setTtl))
            .addAttribute(String.class, a -> a.name("feedPartition")
                .getter(MediaItem::getFeedPartition)
                .setter(MediaItem::setFeedPartition)
                .tags(secondaryPartitionKey("feedPartition-createdAt-index")))
            .addAttribute(Integer.class, a -> a.name("compressionFactor")
                .getter(MediaItem::getCompressionFactor)
                .setter(MediaItem::setCompressionFactor))
            .build();

    private MediaIndexSchemas() {
    }
}
